/*
 * Author: CactusSoft (http://cactussoft.biz/), 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBReader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UINotifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UINotifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBReader.Localization.UINotifications", typeof(UINotifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogue is added to the list..
        /// </summary>
        public static string AddCatalogPage_CatalogAddedSuccess {
            get {
                return ResourceManager.GetString("AddCatalogPage_CatalogAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This catalogue is already in the list..
        /// </summary>
        public static string AddCatalogPage_CatalogAlreadyExists {
            get {
                return ResourceManager.GetString("AddCatalogPage_CatalogAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong address of OPDS catalogue. Make sure it starts with &apos;http://&apos; or &apos;www.&apos;..
        /// </summary>
        public static string AddCatalogPage_InvalidUrlMessage {
            get {
                return ResourceManager.GetString("AddCatalogPage_InvalidUrlMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name or password. Please try again..
        /// </summary>
        public static string AuthorizationPage_WrongPasswordOrUserName {
            get {
                return ResourceManager.GetString("AuthorizationPage_WrongPasswordOrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book was already bought by you..
        /// </summary>
        public static string BuyBook_AlradyBoughtMessage {
            get {
                return ResourceManager.GetString("BuyBook_AlradyBoughtMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books found..
        /// </summary>
        public static string CatalogSearchPage_EmptySearchResult {
            get {
                return ResourceManager.GetString("CatalogSearchPage_EmptySearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops, an error occurred. Please send us error report so we can fix it..
        /// </summary>
        public static string DiagnosticsEmail_Message_Content {
            get {
                return ResourceManager.GetString("DiagnosticsEmail_Message_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DiagnosticsEmail_Message_Title {
            get {
                return ResourceManager.GetString("DiagnosticsEmail_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBReader for Windows Phone.
        /// </summary>
        public static string DiagnosticsEmail_Subject {
            get {
                return ResourceManager.GetString("DiagnosticsEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers &lt;{0}&gt;.
        /// </summary>
        public static string DiagnosticsEmail_To_Format {
            get {
                return ResourceManager.GetString("DiagnosticsEmail_To_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string General_AttentionCaption {
            get {
                return ResourceManager.GetString("General_AttentionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string General_CriticalErrorMessage {
            get {
                return ResourceManager.GetString("General_CriticalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string General_ErrorCaption {
            get {
                return ResourceManager.GetString("General_ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is unavailable. Plese check your Internet connection..
        /// </summary>
        public static string General_NoNetworkMessage {
            get {
                return ResourceManager.GetString("General_NoNetworkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered resource is not an OPDS-catalogue..
        /// </summary>
        public static string General_OpdsFormatErrorCaption {
            get {
                return ResourceManager.GetString("General_OpdsFormatErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting to the catalogue. Make sure the address of OPDS catalogue is valid and check Internet connection..
        /// </summary>
        public static string General_OpdsFormatErrorMessage {
            get {
                return ResourceManager.GetString("General_OpdsFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting to the server. Please check your Internet connection..
        /// </summary>
        public static string General_ServerCommunicationErrorMessage {
            get {
                return ResourceManager.GetString("General_ServerCommunicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during catalogue&apos;s loading. Please check Internet connection and repeat catalogue&apos;s loading..
        /// </summary>
        public static string Read_Catalog_Error_Message {
            get {
                return ResourceManager.GetString("Read_Catalog_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show again.
        /// </summary>
        public static string ShareBook_DontShowAgain {
            get {
                return ResourceManager.GetString("ShareBook_DontShowAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To share a book, it should get uploaded to SkyDrive. Do you want to upload the book to SkyDrive now?.
        /// </summary>
        public static string ShareBook_ShareMessage {
            get {
                return ResourceManager.GetString("ShareBook_ShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during book&apos;s upload. Please try again later..
        /// </summary>
        public static string ShareBook_UploadError {
            get {
                return ResourceManager.GetString("ShareBook_UploadError", resourceCulture);
            }
        }
    }
}
