//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBReader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UISettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UISettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBReader.Localization.UISettings", typeof(UISettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by .
        /// </summary>
        public static string AboutPage_DevelopedBy {
            get {
                return ResourceManager.GetString("AboutPage_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutPage_Version {
            get {
                return ResourceManager.GetString("AboutPage_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use font size from CSS.
        /// </summary>
        public static string SettingPage_CSS_IgnoreFontSize {
            get {
                return ResourceManager.GetString("SettingPage_CSS_IgnoreFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use text alignment from CSS.
        /// </summary>
        public static string SettingPage_CSS_IgnoreMargins {
            get {
                return ResourceManager.GetString("SettingPage_CSS_IgnoreMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS formatting is off.
        /// </summary>
        public static string SettingPage_Formatting_CSS_FontSize_Off {
            get {
                return ResourceManager.GetString("SettingPage_Formatting_CSS_FontSize_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format font size.
        /// </summary>
        public static string SettingPage_Formatting_CSS_FontSize_On {
            get {
                return ResourceManager.GetString("SettingPage_Formatting_CSS_FontSize_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        public static string SettingPage_Formatting_Hyphenation_Off {
            get {
                return ResourceManager.GetString("SettingPage_Formatting_Hyphenation_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string SettingPage_Formatting_Hyphenation_On {
            get {
                return ResourceManager.GetString("SettingPage_Formatting_Hyphenation_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carry over part of a word to the next page.
        /// </summary>
        public static string SettingPage_Hyphenation_Description {
            get {
                return ResourceManager.GetString("SettingPage_Hyphenation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SettingPage_Language_En {
            get {
                return ResourceManager.GetString("SettingPage_Language_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string SettingPage_Language_Ru {
            get {
                return ResourceManager.GetString("SettingPage_Language_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatting.
        /// </summary>
        public static string SettingPage_Pivot_Formatting {
            get {
                return ResourceManager.GetString("SettingPage_Pivot_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string SettingsPage_About {
            get {
                return ResourceManager.GetString("SettingsPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color theme.
        /// </summary>
        public static string SettingsPage_ColorScheme {
            get {
                return ResourceManager.GetString("SettingsPage_ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        public static string SettingsPage_CSS {
            get {
                return ResourceManager.GetString("SettingsPage_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page turning animation.
        /// </summary>
        public static string SettingsPage_Flipping_AnimationStyle {
            get {
                return ResourceManager.GetString("SettingsPage_Flipping_AnimationStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pave turning method.
        /// </summary>
        public static string SettingsPage_Flipping_FlippingMode {
            get {
                return ResourceManager.GetString("SettingsPage_Flipping_FlippingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By pulling.
        /// </summary>
        public static string SettingsPage_FlippingMode_Slide {
            get {
                return ResourceManager.GetString("SettingsPage_FlippingMode_Slide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By tapping.
        /// </summary>
        public static string SettingsPage_FlippingMode_Touch {
            get {
                return ResourceManager.GetString("SettingsPage_FlippingMode_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both.
        /// </summary>
        public static string SettingsPage_FlippingMode_TouchOrSlide {
            get {
                return ResourceManager.GetString("SettingsPage_FlippingMode_TouchOrSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by tapping or pulling.
        /// </summary>
        public static string SettingsPage_FlippingMode_TouchOrSlide_Full {
            get {
                return ResourceManager.GetString("SettingsPage_FlippingMode_TouchOrSlide_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off.
        /// </summary>
        public static string SettingsPage_FlippingStyle_None {
            get {
                return ResourceManager.GetString("SettingsPage_FlippingStyle_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift with overlap.
        /// </summary>
        public static string SettingsPage_FlippingStyle_Overlap {
            get {
                return ResourceManager.GetString("SettingsPage_FlippingStyle_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string SettingsPage_FlippingStyle_Shift {
            get {
                return ResourceManager.GetString("SettingsPage_FlippingStyle_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font.
        /// </summary>
        public static string SettingsPage_Font {
            get {
                return ResourceManager.GetString("SettingsPage_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font on  book reading screen.
        /// </summary>
        public static string SettingsPage_Font_FontFamily {
            get {
                return ResourceManager.GetString("SettingsPage_Font_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        public static string SettingsPage_Font_FontInterval {
            get {
                return ResourceManager.GetString("SettingsPage_Font_FontInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string SettingsPage_Font_FontSize {
            get {
                return ResourceManager.GetString("SettingsPage_Font_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string SettingsPage_Formatting_FlippingMode_Format {
            get {
                return ResourceManager.GetString("SettingsPage_Formatting_FlippingMode_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (size: {1}, spacing: {2:0.0}).
        /// </summary>
        public static string SettingsPage_Formatting_Font_Format {
            get {
                return ResourceManager.GetString("SettingsPage_Formatting_Font_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hide.
        /// </summary>
        public static string SettingsPage_Formatting_Hide {
            get {
                return ResourceManager.GetString("SettingsPage_Formatting_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string SettingsPage_Formatting_Show {
            get {
                return ResourceManager.GetString("SettingsPage_Formatting_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string SettingsPage_General {
            get {
                return ResourceManager.GetString("SettingsPage_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyphenation.
        /// </summary>
        public static string SettingsPage_Hyphenation {
            get {
                return ResourceManager.GetString("SettingsPage_Hyphenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen lock.
        /// </summary>
        public static string SettingsPage_LockScreen {
            get {
                return ResourceManager.GetString("SettingsPage_LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic screen lock.
        /// </summary>
        public static string SettingsPage_LockScreen_Description {
            get {
                return ResourceManager.GetString("SettingsPage_LockScreen_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string SettingsPage_Margin_Big {
            get {
                return ResourceManager.GetString("SettingsPage_Margin_Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string SettingsPage_Margin_Middle {
            get {
                return ResourceManager.GetString("SettingsPage_Margin_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SettingsPage_Margin_None {
            get {
                return ResourceManager.GetString("SettingsPage_Margin_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string SettingsPage_Margin_Small {
            get {
                return ResourceManager.GetString("SettingsPage_Margin_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to margins.
        /// </summary>
        public static string SettingsPage_Margins {
            get {
                return ResourceManager.GetString("SettingsPage_Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application bar.
        /// </summary>
        public static string SettingsPage_Menu {
            get {
                return ResourceManager.GetString("SettingsPage_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application bar is always hidden.
        /// </summary>
        public static string SettingsPage_Menu_Description {
            get {
                return ResourceManager.GetString("SettingsPage_Menu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string SettingsPage_No {
            get {
                return ResourceManager.GetString("SettingsPage_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SettingsPage_Off {
            get {
                return ResourceManager.GetString("SettingsPage_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string SettingsPage_On {
            get {
                return ResourceManager.GetString("SettingsPage_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string SettingsPage_Orientation_Landscape {
            get {
                return ResourceManager.GetString("SettingsPage_Orientation_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape left.
        /// </summary>
        public static string SettingsPage_Orientation_LandscapeLeft {
            get {
                return ResourceManager.GetString("SettingsPage_Orientation_LandscapeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depends on device orientation.
        /// </summary>
        public static string SettingsPage_Orientation_LandscapeOrPortrait {
            get {
                return ResourceManager.GetString("SettingsPage_Orientation_LandscapeOrPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape right.
        /// </summary>
        public static string SettingsPage_Orientation_LandscapeRight {
            get {
                return ResourceManager.GetString("SettingsPage_Orientation_LandscapeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string SettingsPage_Orientation_Portrait {
            get {
                return ResourceManager.GetString("SettingsPage_Orientation_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCREEN ORIENTATION.
        /// </summary>
        public static string SettingsPage_Orientation_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Orientation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to page turning.
        /// </summary>
        public static string SettingsPage_PageFlipping {
            get {
                return ResourceManager.GetString("SettingsPage_PageFlipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen brightness.
        /// </summary>
        public static string SettingsPage_ScreenBrightness {
            get {
                return ResourceManager.GetString("SettingsPage_ScreenBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screen orientation.
        /// </summary>
        public static string SettingsPage_ScreenOrientation {
            get {
                return ResourceManager.GetString("SettingsPage_ScreenOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asphalt.
        /// </summary>
        public static string SettingsPage_Themes_Asphalt {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_Asphalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee.
        /// </summary>
        public static string SettingsPage_Themes_Coffee {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_Coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string SettingsPage_Themes_Day {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey 1.
        /// </summary>
        public static string SettingsPage_Themes_GrayOne {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_GrayOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey 2.
        /// </summary>
        public static string SettingsPage_Themes_GrayTwo {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_GrayTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string SettingsPage_Themes_Night {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepia.
        /// </summary>
        public static string SettingsPage_Themes_Sepia {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_Sepia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky.
        /// </summary>
        public static string SettingsPage_Themes_Sky {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_Sky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string SettingsPage_Themes_TextSample {
            get {
                return ResourceManager.GetString("SettingsPage_Themes_TextSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language of translation.
        /// </summary>
        public static string SettingsPage_TranslateLanguage {
            get {
                return ResourceManager.GetString("SettingsPage_TranslateLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language of UI.
        /// </summary>
        public static string SettingsPage_UILanguage {
            get {
                return ResourceManager.GetString("SettingsPage_UILanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string SettingsPage_Yes {
            get {
                return ResourceManager.GetString("SettingsPage_Yes", resourceCulture);
            }
        }
    }
}
