/*
 * Author: CactusSoft (http://cactussoft.biz/), 2013
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBReader.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBReader.Localization.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddCatalogPage_AppBar_Add {
            get {
                return ResourceManager.GetString("AddCatalogPage_AppBar_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type address of OPDS catalogue.
        /// </summary>
        public static string AddCatalogPage_EnterCatalogUrl {
            get {
                return ResourceManager.GetString("AddCatalogPage_EnterCatalogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string AddCatalogPage_EnterCatalogUrlWatermark {
            get {
                return ResourceManager.GetString("AddCatalogPage_EnterCatalogUrlWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AddCatalogPage_LowTitle {
            get {
                return ResourceManager.GetString("AddCatalogPage_LowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETWORK LIBRARY.
        /// </summary>
        public static string AddCatalogPage_TopTitle {
            get {
                return ResourceManager.GetString("AddCatalogPage_TopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books found..
        /// </summary>
        public static string AllCatalogPage_EmptySearchResult {
            get {
                return ResourceManager.GetString("AllCatalogPage_EmptySearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH IN NETWORK LIBRARY.
        /// </summary>
        public static string AllCatalogsSearchPage_Title {
            get {
                return ResourceManager.GetString("AllCatalogsSearchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in network library.
        /// </summary>
        public static string AllCatalogsSearchPageViewModel_Title {
            get {
                return ResourceManager.GetString("AllCatalogsSearchPageViewModel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBar_AddBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_AddBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buy.
        /// </summary>
        public static string AppBar_BuyBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_BuyBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete demo.
        /// </summary>
        public static string AppBar_DeleteBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_DeleteBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string AppBar_DownloadBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_DownloadBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download demo.
        /// </summary>
        public static string AppBar_DownloadTrialBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_DownloadTrialBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite.
        /// </summary>
        public static string AppBar_FavoritesBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_FavoritesBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string AppBar_LoginBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_LoginBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate.
        /// </summary>
        public static string AppBar_RateBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_RateBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read.
        /// </summary>
        public static string AppBar_ReadBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_ReadBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read demo.
        /// </summary>
        public static string AppBar_ReadTrialBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_ReadTrialBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBar_SearchBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_SearchBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string AppBar_SendEmailBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_SendEmailBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBar_SettingsMenuItem_Text {
            get {
                return ResourceManager.GetString("AppBar_SettingsMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string AppBar_ShareBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_ShareBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorting.
        /// </summary>
        public static string AppBar_SortBtn_Text {
            get {
                return ResourceManager.GetString("AppBar_SortBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AuthorizationPage_PasswordText {
            get {
                return ResourceManager.GetString("AuthorizationPage_PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZATION.
        /// </summary>
        public static string AuthorizationPage_TopTitle {
            get {
                return ResourceManager.GetString("AuthorizationPage_TopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string AuthorizationPage_UserNameText {
            get {
                return ResourceManager.GetString("AuthorizationPage_UserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download error.
        /// </summary>
        public static string BookDownloader_Error {
            get {
                return ResourceManager.GetString("BookDownloader_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book is downloaded.
        /// </summary>
        public static string BookDownloader_Success {
            get {
                return ResourceManager.GetString("BookDownloader_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BookInfo_Annotation {
            get {
                return ResourceManager.GetString("BookInfo_Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string BookInfo_Author {
            get {
                return ResourceManager.GetString("BookInfo_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string BookInfo_Categories {
            get {
                return ResourceManager.GetString("BookInfo_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string BookInfo_Language {
            get {
                return ResourceManager.GetString("BookInfo_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string BookInfoPage_Loading {
            get {
                return ResourceManager.GetString("BookInfoPage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string BookInfoPage_Price {
            get {
                return ResourceManager.GetString("BookInfoPage_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARE.
        /// </summary>
        public static string BookInfoPage_SelectSharingMethodTitle {
            get {
                return ResourceManager.GetString("BookInfoPage_SelectSharingMethodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string BookInfoPage_Title {
            get {
                return ResourceManager.GetString("BookInfoPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string BookInfoPage_Type {
            get {
                return ResourceManager.GetString("BookInfoPage_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH IN BOOKMARKS.
        /// </summary>
        public static string BookmarkSearchPage_Title {
            get {
                return ResourceManager.GetString("BookmarkSearchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of bookmarks is empty.
        /// </summary>
        public static string BookmarksPivot_AllBook_EmptyList {
            get {
                return ResourceManager.GetString("BookmarksPivot_AllBook_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all books.
        /// </summary>
        public static string BookmarksPivot_AllBooks {
            get {
                return ResourceManager.GetString("BookmarksPivot_AllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of bookmarks is empty.
        /// </summary>
        public static string BookmarksPivot_AllBooks_EmptyList {
            get {
                return ResourceManager.GetString("BookmarksPivot_AllBooks_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to current book.
        /// </summary>
        public static string BookmarksPivot_ThisBook {
            get {
                return ResourceManager.GetString("BookmarksPivot_ThisBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of bookmarks is empty.
        /// </summary>
        public static string BookmarksPivot_ThisBook_EmptyList {
            get {
                return ResourceManager.GetString("BookmarksPivot_ThisBook_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOKMARKS.
        /// </summary>
        public static string BookmarksPivot_Title {
            get {
                return ResourceManager.GetString("BookmarksPivot_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Catalog for Manybooks.net.
        /// </summary>
        public static string Catalog_Manybooks_Description {
            get {
                return ResourceManager.GetString("Catalog_Manybooks_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManyBooks.net.
        /// </summary>
        public static string Catalog_Manybooks_Title {
            get {
                return ResourceManager.GetString("Catalog_Manybooks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to read, what to see, where to go, how to live :).
        /// </summary>
        public static string Catalog_Prochtenie_Description {
            get {
                return ResourceManager.GetString("Catalog_Prochtenie_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochtenie.
        /// </summary>
        public static string Catalog_Prochtenie_Title {
            get {
                return ResourceManager.GetString("Catalog_Prochtenie_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log out.
        /// </summary>
        public static string CatalogPage_Logout_MenuItem {
            get {
                return ResourceManager.GetString("CatalogPage_Logout_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string CatalogPage_Refresh_MenuItem {
            get {
                return ResourceManager.GetString("CatalogPage_Refresh_MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH IN {0}.
        /// </summary>
        public static string CatalogSearchPage_Title {
            get {
                return ResourceManager.GetString("CatalogSearchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to network library.
        /// </summary>
        public static string CatalogsView_Title {
            get {
                return ResourceManager.GetString("CatalogsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTENT.
        /// </summary>
        public static string ContentsPage_Title {
            get {
                return ResourceManager.GetString("ContentsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOADS.
        /// </summary>
        public static string DownloadListPage_Title {
            get {
                return ResourceManager.GetString("DownloadListPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DownloadsListPage_Delete {
            get {
                return ResourceManager.GetString("DownloadsListPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No downloads in progress..
        /// </summary>
        public static string DownloadsListPage_Empty {
            get {
                return ResourceManager.GetString("DownloadsListPage_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat.
        /// </summary>
        public static string DownloadsListPage_Restart {
            get {
                return ResourceManager.GetString("DownloadsListPage_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string DownloadStatus_Completed {
            get {
                return ResourceManager.GetString("DownloadStatus_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string DownloadStatus_Downloading {
            get {
                return ResourceManager.GetString("DownloadStatus_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DownloadStatus_Error {
            get {
                return ResourceManager.GetString("DownloadStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string DownloadStatus_Parsing {
            get {
                return ResourceManager.GetString("DownloadStatus_Parsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string DownloadStatus_Pending {
            get {
                return ResourceManager.GetString("DownloadStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string EditBookPage_AppBar_MakeNewTitle {
            get {
                return ResourceManager.GetString("EditBookPage_AppBar_MakeNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a new book title.
        /// </summary>
        public static string EditBookPage_MakeNewTitle {
            get {
                return ResourceManager.GetString("EditBookPage_MakeNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string EditBookPage_Subtitle {
            get {
                return ResourceManager.GetString("EditBookPage_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book community.
        /// </summary>
        public static string Flibusta_Catalog_Description {
            get {
                return ResourceManager.GetString("Flibusta_Catalog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flibusta.
        /// </summary>
        public static string Flibusta_Catalog_Title {
            get {
                return ResourceManager.GetString("Flibusta_Catalog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One click away from a book.
        /// </summary>
        public static string Litres_Catalog_Descritption {
            get {
                return ResourceManager.GetString("Litres_Catalog_Descritption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Litres.
        /// </summary>
        public static string Litres_Catalog_Title {
            get {
                return ResourceManager.GetString("Litres_Catalog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        public static string MainPage_AppBarMenu_Downloads {
            get {
                return ResourceManager.GetString("MainPage_AppBarMenu_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FBReader.
        /// </summary>
        public static string MainPage_PanoramaTitle {
            get {
                return ResourceManager.GetString("MainPage_PanoramaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string MessageBox_NoBtn {
            get {
                return ResourceManager.GetString("MessageBox_NoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string MessageBox_YesBtn {
            get {
                return ResourceManager.GetString("MessageBox_YesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string ProgressBar_Text {
            get {
                return ResourceManager.GetString("ProgressBar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string ReadPage_AppBar_Apply {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to book info.
        /// </summary>
        public static string ReadPage_AppBar_BookInfo {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_BookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmarks.
        /// </summary>
        public static string ReadPage_AppBar_Bookmarks {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ReadPage_AppBar_Cancel {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color theme.
        /// </summary>
        public static string ReadPage_AppBar_ColorScheme {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_ColorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from  favorite.
        /// </summary>
        public static string ReadPage_AppBar_FromFavorites {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_FromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to start.
        /// </summary>
        public static string ReadPage_AppBar_Pin {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string ReadPage_AppBar_Search {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string ReadPage_AppBar_Settings {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string ReadPage_AppBar_Share {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        public static string ReadPage_AppBar_TableOfContent {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_TableOfContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorite.
        /// </summary>
        public static string ReadPage_AppBar_ToFavorites {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_ToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom in.
        /// </summary>
        public static string ReadPage_AppBar_ZoomIn {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zoom out.
        /// </summary>
        public static string ReadPage_AppBar_ZoomOut {
            get {
                return ResourceManager.GetString("ReadPage_AppBar_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bookmark colour.
        /// </summary>
        public static string ReadPage_Bookmark_SelectColor {
            get {
                return ResourceManager.GetString("ReadPage_Bookmark_SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All books from your SD-card..
        /// </summary>
        public static string SDCard_Catalog_Description {
            get {
                return ResourceManager.GetString("SDCard_Catalog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD-card.
        /// </summary>
        public static string SDCard_Catalog_Title {
            get {
                return ResourceManager.GetString("SDCard_Catalog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results..
        /// </summary>
        public static string SearchInBook_EmptyList {
            get {
                return ResourceManager.GetString("SearchInBook_EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH IN BOOK {0}.
        /// </summary>
        public static string SearchInBookPage_Title {
            get {
                return ResourceManager.GetString("SearchInBookPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books found..
        /// </summary>
        public static string SearchPage_IsEmptyText {
            get {
                return ResourceManager.GetString("SearchPage_IsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH IN MY LIBRARY.
        /// </summary>
        public static string SearchPage_Title {
            get {
                return ResourceManager.GetString("SearchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Sharing_Email {
            get {
                return ResourceManager.GetString("Sharing_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote from &quot;{0}&quot;.
        /// </summary>
        public static string Sharing_QuoteFormat {
            get {
                return ResourceManager.GetString("Sharing_QuoteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social networks.
        /// </summary>
        public static string Sharing_Social {
            get {
                return ResourceManager.GetString("Sharing_Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloud storage.
        /// </summary>
        public static string SkyDrive_Catalog_Description {
            get {
                return ResourceManager.GetString("SkyDrive_Catalog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDrive.
        /// </summary>
        public static string SkyDrive_Catalog_Title {
            get {
                return ResourceManager.GetString("SkyDrive_Catalog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the translation. The word(s) being translated might be missing in the dictionary..
        /// </summary>
        public static string TranslateError_Body {
            get {
                return ResourceManager.GetString("TranslateError_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TranslateError_Title {
            get {
                return ResourceManager.GetString("TranslateError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all books.
        /// </summary>
        public static string UserLibararyView_AllBooksButton_Content {
            get {
                return ResourceManager.GetString("UserLibararyView_AllBooksButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By author.
        /// </summary>
        public static string UserLibraryPage_AuthorSortMode {
            get {
                return ResourceManager.GetString("UserLibraryPage_AuthorSortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not added any book to the list of favorite..
        /// </summary>
        public static string UserLibraryPage_Favs_Empty {
            get {
                return ResourceManager.GetString("UserLibraryPage_Favs_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAVORITE.
        /// </summary>
        public static string UserLibraryPage_FavsTitle {
            get {
                return ResourceManager.GetString("UserLibraryPage_FavsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By name.
        /// </summary>
        public static string UserLibraryPage_NameSortMode {
            get {
                return ResourceManager.GetString("UserLibraryPage_NameSortMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete from favorite.
        /// </summary>
        public static string UserLibraryPage_RemoveFromFavourites {
            get {
                return ResourceManager.GetString("UserLibraryPage_RemoveFromFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SORT.
        /// </summary>
        public static string UserLibraryPage_Sorting {
            get {
                return ResourceManager.GetString("UserLibraryPage_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY LIBRARY.
        /// </summary>
        public static string UserLibraryPage_Title {
            get {
                return ResourceManager.GetString("UserLibraryPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to search in network library to find necessary book..
        /// </summary>
        public static string UserLibraryView_NoItemsText {
            get {
                return ResourceManager.GetString("UserLibraryView_NoItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my library.
        /// </summary>
        public static string UserLibraryView_Title {
            get {
                return ResourceManager.GetString("UserLibraryView_Title", resourceCulture);
            }
        }
    }
}
